config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :notifications
  resources :rehabilitations, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :rehabilitation_comments, only: [:create, :destroy]
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :rehabilitation
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @rehabilitation = Rehabilitation.find(params[:rehabilitation_id])
    favorite = current_user.favorites.new(rehabilitation_id: @rehabilitation.id)
    favorite.save
  end

  def destroy
    @rehabilitation = Rehabilitation.find(params[:rehabilitation_id])
    favorite = current_user.favorites.find_by(rehabilitation_id: @rehabilitation.id)
    favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite-btn.html.erb
<% if rehabilitation.favorited_by?(current_user) %>
  <h5><strong>いいね</strong>
    <%= link_to rehabilitation_favorites_path(rehabilitation.id), method: :delete, remote: true do %>
      ♥<%= rehabilitation.favorites.count %>
    <% end %>
  </h5>
  <% else %>
  <h5><strong>いいね</strong>
    <%= link_to rehabilitation_favorites_path(rehabilitation.id), method: :post, remote: true do %>
      ♡<%= rehabilitation.favorites.count %>
    <% end %>
  </h5>
<% end %>

app/views/favorites/create.js.erb
$(".favorite-btn").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {rehabilitation: @rehabilitation}) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn").html("<%= escape_javascript(render partial: 'favorites/favorite-btn', locals: {rehabilitation: @rehabilitation}) %>");