config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :notifications
  resources :rehabilitations, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :rehabilitation_comments, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def self.guest
    find_or_create_by!(name: 'ゲスト', name_kana: 'ゲスト', affiliation: 'ゲスト病院', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  has_many :rehabilitations, dependent: :destroy
  attachment :profile_image
  has_many :rehabilitation_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :active_notifications, class_name: "Notification", foreign_key: "visiter_id", dependent: :destroy
  has_many :passive_notifications, class_name: "Notification", foreign_key: "visited_id", dependent: :destroy

  validates :name, presence: true, length: { maximum: 20, minimum: 2 }
  validates :name_kana, presence: true, length: { maximum: 20, minimum: 2 }
  validates :affiliation, presence: true, length: { maximum: 20 }
  validates :email, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to rehabilitations_path, notice: 'ゲストユーザーとしてログインしました'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user
  before_action :ensure_normal_user, only: %i(update destroy)

  def show
    @user = User.find(params[:id])
    @rehabilitations = @user.rehabilitations.page(params[:page]).reverse_order
    @notifications = Notification.where(checked: false, visited_id: current_user.id)
    if @notifications.present?
      @notifications.each do |notification|
        notification.update_attributes(checked: true)
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報が更新されました"
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path, notice: "ユーザーが削除されました"
  end

  private

  def user_params
    params.require(:user).permit(:name, :name_kana, :affiliation, :introduction, :profile_image, :email)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_normal_user
    if current_user.email == 'guest@example.com'
      flash[:notice] = 'ゲストユーザーの更新・削除はできません'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <h2><strong>ユーザー編集</strong></h2>
  <div class="error-messages">
    <% if @user.errors.any? %>
      <h5><%= @user.errors.count %>件のエラーが発生しました</h5>
      <% @user.errors.full_messages.each do |message| %><br>
        ・<%= message %>
        <% end %>
    <% end %>
  </div>
  <div class='row'>
    <div class='col-md-12'>
      <%= form_with model:@user, local:true do |f| %>
        <p class="field">
          <%= f.label :氏名 %><br>
          <%= f.text_field :name, placeholder:"言語 太郎" %>
        </p>
        <p class="field">
          <%= f.label :氏名（カナ） %><br>
          <%= f.text_field :name_kana, placeholder:"ゲンゴ タロウ" %>
        </p>
        <p class="field">
          <%= f.label :メールアドレス %><br>
          <%= f.email_field :email, placeholder:"..@.." %>
        </p>
        <p class="field">
          <%= f.label :所属 %><br>
          <%= f.text_field :affiliation, placeholder:"◯◯病院"%>
        </p>
        <p class="field">
          <%= f.label :紹介文 %><br>
          <%= f.text_area :introduction,rows:'4', cols:"30", placeholder:"経歴、STとしてのモットー、座右の銘などを50文字以下でご記入ください" %>
        </p>
        <p class="field">
          <%= f.label :ユーザー画像 %><br>
          <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg"%>
          <%= f.attachment_field :profile_image, placeholder: "ユーザー画像" %>
        </p>
        <p class="text-center">
          <%= f.submit "変更する", class: "btn btn-success" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class='row'>
    <div class='col-md-3'>
      <h2><strong>マイページ</strong></h2>
      <h4><strong><%= @user.name %></strong></h4>
      <%= attachment_image_tag @user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>
      <h6><strong>所属</strong><br><%= @user.affiliation %></h6>
      <h6><strong>紹介</strong><br><%= @user.introduction %></h6>
      <% if @user.id == current_user.id %>
        <p><%= link_to "ユーザー情報編集", edit_user_path(@user.id) %></p>
        <p><%= link_to "退会する",user_path(@user.id),method: :delete, "data-confirm" => "本当に退会しますか？" %></p>
      <% end %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <div class='text-right'>
        <%= link_to "訓練新規投稿", new_rehabilitation_path, class: "btn btn-primary" %>
      </div>
      <h3>投稿した訓練</h3>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>訓練名</th>
            <th>♥</th>
            <th>コメント</th>
            <th>投稿日時</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @rehabilitations.each do |rehabilitation| %>
            <tr>
              <td><%= link_to rehabilitation_path(rehabilitation.id) do %>
                <%= rehabilitation.training_name %>
                <% end %>
              </td>
              <td><%= rehabilitation.favorites.count %></td>
              <td><%= rehabilitation.rehabilitation_comments.count %>件</td>
              <td><%= rehabilitation.created_at.to_s(:datetime) %></td>
              <td><% if rehabilitation.user == current_user %>
                <%= link_to "編集", edit_rehabilitation_path(rehabilitation.id), class: "btn btn-warning" %>
                <%= link_to "削除", rehabilitation_path(rehabilitation.id,page: "mypage"), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
                <% end %>
              </td>
            </tr>
          <% end %>
          <%= paginate @rehabilitations %>
        </tbody>
      </table>
    </div>
  </div>
</div>