config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :notifications
  resources :rehabilitations, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :rehabilitation_comments, only: [:create, :destroy]
  end
end

app/models/rehabilitation_comment.rb
class RehabilitationComment < ApplicationRecord
  belongs_to :user
  belongs_to :rehabilitation
  has_many :notifications

  validates :comment, presence: true

  def create_notification(visited_id, visiter_id, comment_id)
    notification = Notification.new({
      visiter_id: visiter_id,
      visited_id: visited_id,
      rehabilitation_comment_id: comment_id,
      checked: false,
    })
    notification.save
  end
end

app/controllers/rehabilitation_comments_controller.rb
class RehabilitationCommentsController < ApplicationController
  def create
    @rehabilitation = Rehabilitation.find(params[:rehabilitation_id])
    @new_rehabilitation_comment = RehabilitationComment.new
    comment = current_user.rehabilitation_comments.new(rehabilitation_comment_params)
    comment.rehabilitation_id = @rehabilitation.id
    comment.score = Language.get_data(rehabilitation_comment_params[:comment])
    if comment.save
      comment.create_notification(Rehabilitation.find(comment.rehabilitation_id).user_id, current_user.id, comment.id)
    end
  end

  def destroy
    @rehabilitation = Rehabilitation.find(params[:rehabilitation_id])
    @new_rehabilitation_comment = RehabilitationComment.new
    comment = current_user.rehabilitation_comments.find(params[:id])
    comment.destroy
  end

  private

  def rehabilitation_comment_params
    params.require(:rehabilitation_comment).permit(:comment, :reply_comment)
  end
end

app/helpers/rehabilitation_comments_helper.rb
module RehabilitationCommentsHelper
end

app/views/rehabilitation_comments/_comment.html.erb
<%= attachment_image_tag rehabilitation_comment.user, :profile_image, size: "60x60", fallback: "no_image.jpg" %>
<%= rehabilitation_comment.user.name %><br>
<%= rehabilitation_comment.comment %><br>
<%= rehabilitation_comment.created_at.to_s(:datetime) %><br>
<span class="sentiment-score">感情分析スコア<%= rehabilitation_comment.score %></span>
<% if rehabilitation_comment.user == current_user %>
  <%= link_to "コメントを削除", rehabilitation_rehabilitation_comment_path(rehabilitation_comment.rehabilitation, rehabilitation_comment), method: :delete, remote: true, "data-confirm" => "本当に削除しますか？" %>
<% end %>

app/views/rehabilitation_comments/_comments.html.erb
<% rehabilitation_comments = rehabilitation.rehabilitation_comments.order(id: "DESC") %>
<!--parents＝親になるコメントのid-->
<% parents = [] %>
<% rehabilitation_comments.each do |rehabilitation_comment| %>
  <p>
    <%= render 'rehabilitation_comments/parent_comment', rehabilitation_comments: rehabilitation_comments, rehabilitation_comment: rehabilitation_comment, parents: parents %>
    <!--#親として出力されていたら除外する-->
    <% if parents.exclude?(rehabilitation_comment.id) %>
      <%= render 'rehabilitation_comments/comment', rehabilitation_comment: rehabilitation_comment %>
      <%= form_with(model:[rehabilitation, new_rehabilitation_comment]) do |f| %>
        <%= f.text_area :comment, rows:'3', cols:"20", placeholder: "コメントへの返信" %><br>
        <%= f.hidden_field :reply_comment, :value => rehabilitation_comment.id  %>
        <%= f.submit "コメントする" %>
      <% end %>
    <% end %>
  </p>
<% end %>

app/views/rehabilitation_comments/_new_comment.html.erb
<%= form_with(model:[rehabilitation, rehabilitation_comment]) do |f| %>
  <%= f.text_area :comment, rows:'5', cols:"30", placeholder: "意見・質問等" %><br>
  <%= f.submit "コメントする" %>
<% end %>

app/views/rehabilitation_comments/_parent_comment.html.erb
<% if rehabilitation_comment.reply_comment.present? %>
  <% parent_comment = rehabilitation_comments.find(rehabilitation_comment.reply_comment) %>
  <%= render 'rehabilitation_comments/parent_comment', rehabilitation_comments: rehabilitation_comments, rehabilitation_comment: parent_comment, parents: parents %>
  <%= render 'rehabilitation_comments/comment', rehabilitation_comment: parent_comment %>
  <br>
  <% parents.push(rehabilitation_comment.reply_comment) %>
<% end %>

app/views/rehabilitation_comments/create.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'rehabilitation_comments/comments', locals: {rehabilitation: @rehabilitation, new_rehabilitation_comment: @new_rehabilitation_comment}) %>");
$("textarea").val('')

app/views/rehabilitation_comments/destroy.js.erb
$(".comments").html("<%= escape_javascript(render partial: 'rehabilitation_comments/comments', locals: {rehabilitation: @rehabilitation, new_rehabilitation_comment: @new_rehabilitation_comment}) %>");