config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  root to: 'homes#top'
  get 'homes/about'
  resources :users, only: [:show, :edit, :update, :destroy]
  resources :notifications
  resources :rehabilitations, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :rehabilitation_comments, only: [:create, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STリハ辞書</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="description" content="言語聴覚士のための訓練内容投稿サイト">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="<%= request.path_info == "/" ? "wrapper" : "" %>" class="d-flex flex-column vh-100" style="background-color:#feffde;">
    <header class="shadow-sm" style="background-color:#ddffbc;">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <% if user_signed_in? %>
            <h6><%= link_to "STリハ辞書", rehabilitations_path, class: 'navbar-brand' %></h6>
          <% else %>
            <h6><%= link_to "STリハ辞書", root_path, class: 'navbar-brand' %></h6>
          <% end %>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="search_field">
              <% if user_signed_in? %>
                <%= search_form_for @search do |f| %>
                  <%= f.label'訓練検索' %>
                  <%= f.search_field :training_name_or_speech_pathological_findings_or_adaptation_precautions_cont, required:"true", placeholder:'訓練、所見、適応' %>
                  <%= f.submit "検索" %>
                <% end %>
              <% end %>
            </div>
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <% if !Notification.where(checked: false, visited_id: current_user.id).blank? %>
                  <li class="nav-item">
                    <%= link_to '', user_path(current_user.id), class: 'fas fa-bell' %>
                  </li>
                <% end %>
                <li class="nav-item">
                  <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark fas fa-smile' %>
                </li>
                <li class="nav-item">
                  <%= link_to '訓練一覧', rehabilitations_path,class: 'nav-link text-dark fas fa-hand-holding-medical' %>
                </li>
                <li class="nav-item">
                  <%= link_to '新規投稿', new_rehabilitation_path,class: 'nav-link text-dark fas fa-plus' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class: 'nav-link text-dark fas fa-sign-out-alt' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Top', root_path,class: 'nav-link text-dark fas fa-brain' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'About', homes_about_path,class: 'nav-link text-dark fas fa-stethoscope' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path,class: 'nav-link text-dark fas fa-sign-in-alt'%>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path,class: 'nav-link text-dark fas fa-user-plus' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <p class="notice" style="text-align:center;"><%= notice %></p>
      <%= yield %>
    </main>
    <footer class="text-dark pt-4 pb-2" style="background-color:#ddffbc;">
      <p class="text-center">©2021 STリハ辞書</p>
    </footer>
  </body>

</html>